# docker-compose file for creating a local development environment
version: '2'
services:
  db:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: chatty_pie_connector

  smtp:
    image: greenmail/standalone:1.5.2
    ports:
      - "3025:3025"
