# Don't forget to point this to your own chatty-pie instance
chatty.pie.host: https://chattypie-148413.appspot.com
chatroom.report.subscriber: chatty.pie.team@yopmail.com
# default credentials. Can be overridden through environment variables 
connector.allowed.credentials: very-secure:password,search-1533:PrTW5GrHn6WNHHxt

#Override this if the address of the connector instance is using https, otherwise the oauth request validation 
#will fail
signature.validation.use.https: false
spring.datasource:
    #See http://stackoverflow.com/questions/7605953/how-to-change-mysql-timezone-in-java-connection for explanation 
    #on the `useLegacyDatetimeCode` parameter
    url: jdbc:mysql://localhost/chatty_pie_connector?useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: ""

spring.mail:
    host: localhost
    port: 3025

endpoints:
  enabled: false
  info:
    enabled: true
    sensitive: false
  health:
      enabled: true
      sensitive: false
      time-to-live: 5000

info:
  build:
    name: @project.name@
    description: @project.description@
    version: @project.version@

management:
  security:
    enabled: false
